<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>OrdnerSync.App</AssemblyName>
    <Product>OrdnerSync</Product>
    <ApplicationIcon>Assets\OrdnerSync.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KassenSync.Core\KassenSync.Core.csproj" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
    <Resource Include="Assets\OrdnerSync.ico" />
    <Resource Include="Assets\OrdnerSyncIcon.png" />
    <Resource Include="Assets\OrdnerSyncLogoFull.png" />
  </ItemGroup>
</Project>
